"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class gps_t(object):
    __slots__ = ["timestamp", "lat", "lat_dir", "lon", "lon_dir", "altitude", "utm_x", "utm_y"]

    def __init__(self):
        self.timestamp = 0.0
        self.lat = 0.0
        self.lat_dir = ""
        self.lon = 0.0
        self.lon_dir = ""
        self.altitude = 0.0
        self.utm_x = 0.0
        self.utm_y = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(gps_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ff", self.timestamp, self.lat))
        __lat_dir_encoded = self.lat_dir.encode('utf-8')
        buf.write(struct.pack('>I', len(__lat_dir_encoded)+1))
        buf.write(__lat_dir_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">f", self.lon))
        __lon_dir_encoded = self.lon_dir.encode('utf-8')
        buf.write(struct.pack('>I', len(__lon_dir_encoded)+1))
        buf.write(__lon_dir_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">fff", self.altitude, self.utm_x, self.utm_y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gps_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gps_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = gps_t()
        self.timestamp, self.lat = struct.unpack(">ff", buf.read(8))
        __lat_dir_len = struct.unpack('>I', buf.read(4))[0]
        self.lat_dir = buf.read(__lat_dir_len)[:-1].decode('utf-8', 'replace')
        self.lon = struct.unpack(">f", buf.read(4))[0]
        __lon_dir_len = struct.unpack('>I', buf.read(4))[0]
        self.lon_dir = buf.read(__lon_dir_len)[:-1].decode('utf-8', 'replace')
        self.altitude, self.utm_x, self.utm_y = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if gps_t in parents: return 0
        tmphash = (0x3be1f23e2afe8cfe) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if gps_t._packed_fingerprint is None:
            gps_t._packed_fingerprint = struct.pack(">Q", gps_t._get_hash_recursive([]))
        return gps_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

